services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.11-py3
    container_name: triton_sbd_server
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # gRPC
      - "8002:8002"  # Metrics
    volumes:
      - .:/models
    shm_size: '1gb'
    command: >
      tritonserver
      --model-repository=/models
      --model-control-mode=explicit
      --load-model=model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all