name: "model"
backend: "fil"
max_batch_size: 51200

input [
  {
    name: "input__0"        # dont change
    data_type: TYPE_FP32
    dims: [ 20 ]       # per-sample feature size; batch dim will be added by Triton
  }
]

output [
  {
    name: "output__0"       # dont change
    data_type: TYPE_FP32
    dims: [ 2 ]        # per-sample [p0, p1]; batch dim added by Triton
  }
]

instance_group [
  {
    kind: KIND_AUTO
    count: 1
  }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16, 32, 64 ]
  max_queue_delay_microseconds: 5000  # 2 ms
}

parameters {
  key: "model_type"
  value { string_value: "treelite_checkpoint" }
}
parameters {
  key: "predict_proba"
  value { string_value: "true" }
}
parameters {
  key: "output_class"
  value { string_value: "false" }
}
parameters {
  key: "model_filename"
  value { string_value: "checkpoint.tl" }
}
